name: satre-feature-survey
channels:
  - conda-forge
dependencies:
  - ipython=8.8.0
  - jupyterlab=3.5.2
  - matplotlib=3.6.2
  - nbconvert=7.3.1
  - numpy=1.24.1
  - openpyxl=3.1.1
  - pandas=1.5.2
  - python=3.10.8
  - wordcloud=1.9.1.1
